.Dd December 5, 2024
.Dt NAKIDAI.RU 7
.Os Nakidai
.
.Sh NAME
.Nm nakidai
.Nd C & Python developer
.
.Sh SYNOPSIS
.Nm pronouns
.Lk https://pronouns.nakidai.ru/
.Nm mail
.Mt nakidai@disroot.org
.Nm discord
.Lk https://discord.com/users/596659213124763649
.Nm own git instance (abandoned a bit)
.Lk https://git.nakidai.ru/nakidai
.Nm github
.Lk https://github.com/nakidai
.
.Sh DESCRIPTION
I grew out
of computer games.
Instead,
I enjoy programming
and exploring unix.
I do love
.Ox
and everything
related to it.
Have IBM and
Lenovo
thinkpad,
both running
.Ox
:3
.
.Pp
I enjoy writing my projects
in
.Xr python 1
and
.Xr cc 1 ,
maybe
sometimes
.Xr sh 1 .
My projects are usually
small yet useful
.Pq for me
scripts.
.
.Pp
These are
some projects
I've written:
.Bl -tag -width Ds
.It Lk https://ptc.pwn3t.ru PetTheCord
Thing for petting Discord users
.It Lk https://github.com/latexds LaTeXDS
LaTeX renderer in Discord
.It Lk https://github.com/nakidai/stp stp
SVG renderer in web
.It Lk https://github.com/nakidai/batper batper
Show battaries' percentage on
.Ox
systems
.Po
somewhy
I couldn't find a tool
with that simple functionality
.Pc
.It Lk https://github.com/nakidai/NotABot NotABot
QoL bot for Vectozavr's Discord server
.It Lk https://github.com/nakidai/MQEC MQEC
.Lk https://github.com/UltraQbik/SMC-MQ-CPU MQ
emulator
.It Lk https://git.nakidai.ru/nakidai/mycfetch mycfetch
Simple system fetch tool
.It Lk https://github.com/nakidai/libhttpc LibHTTPC
Server-side QoL HTTP library
.El
.
.Pp
This is my GPG key
for commit signing:
.Bl -bullet
.It
.Lk https://nakidai.ru/nakidai.asc download (nakidai.ru)
.El
.Bd -literal
-----BEGIN PGP PUBLIC KEY BLOCK-----
Comment: Nakidai Perumenei <nakidai@disroot.org>
Comment:   C & Python developer
Comment: Fingerprint:   F1730848189DAA2BEECC05FCC6BF6082F42307C0


mQINBGbkNaoBEACkziOd6YlHJCgMMgrQ+2biswtpQrnE/RNMNn0CS62dDoqylRgk
UYFT9Lggba9+z/oedhpVRy4EnWOo+GfkGlDQ2hrFsN2F6jBZT1wNr1pbGmbpCKCa
WpMm3MU9Pm0dEWPE4n/IIuE64FQnd/ag0rA9WEyOS6Gegp6dm75LhwTKJX85guQ5
qJLNP4lNwKEqaWswRxawyAacqacpJdFOqG0pSJhWnYyfJKBfqehLAVwB0BHT8cb6
lK63nvnT/RLwIiMSKwpBIZCk7L76P1WBEmgnHe9PkQNKi6Q0y6Tc+ngEYhb+erwV
oo62x8b4pXxmsZQXkpzBfeaqdKfkx4lMgxRQJYpn7cMp+VD4Q+uBY4f+ttjVDAmH
dLtQBDAR1f2hFPgrFNGP+noLDK+5+r6inIxE63VpXtUgdYYQnAotyfcf0wp5pG20
+JXRfzymlmg7ctWV4zzZsPKiN3rqgIzdAKNCtOlrLMXVVZALQQ5y12YMgWXFFnIz
29RVkbDA90vPs+FdfUXPNtAXC1kOnv6HErYN8dppaf4ryRk2V3+sD5RHL6LXSDca
R7vy2TYmYZ8/AMmvRzgAzq2SC3ni2mWcWirf+PNjg8IumE7y/Mg5l8+q0lKKP7kD
V1pBCcHhr9ZZEZU8cU3vYNxlZjfwHkAMBlA3jDJYV2E5iZaEbW5PnvkZnwARAQAB
tCdOYWtpZGFpIFBlcnVtZW5laSA8bmFraWRhaUBkaXNyb290Lm9yZz6JAlEEEwEI
ADsWIQTxcwhIGJ2qK+7MBfzGv2CC9CMHwAUCZuQ1qgIbAwULCQgHAgIiAgYVCgkI
CwIEFgIDAQIeBwIXgAAKCRDGv2CC9CMHwNKgD/48x6o+S30Sx71JWMA4G+eDZ+Tk
nEQbx1WdaZVIjNVqbQ+mrvO+gHfVmZCTQN1+zzRlbJPaycolTbS0JCEIhzZgPTYp
46hdLdkDLhQZd0JyIgkHed3ibLsF8Aa6vwrgeACupwnBQJMXuhDXjlaBT6p8a6bv
2I340AQrByC0YdjQRGRbXAYdm67flEMk8ifJoY9rPaPWMVzJK+C/PRQn072PiTW4
GA1xHN8h7RYVceUEj7m7IOIGCtDdTLEP7RJtV/wQM65WyZvRLO+KGaOHurZJzyED
rZGtqYAa5jrYV6vj3kY4qVLZPSBiGCsoVmTmkID5xdGF7Bkj0AH1+my3SQDMMSuk
ltmWAUprxsOyVYi/36cUs6D7/ajkvlKCo9cYZ6q8JpzpTUwLPQGfXi5eim/hI4lc
cjCjd5D3VXoMll8oDXo5upACVbUQ8NKWJTefwZg+p8urdDaHg/nXngZUyhfYHvvY
k3dmUjnq9HkiNjHgNeVH8t8ItEmK57BKIRb1SQB8OvLfXCKeDMKypwzTAhCDM+As
8DV/u/HbLcKsCj9q84inDQY5zJxKsnCN/WowqxHjqaoEpntPiAqxcmpQ3V7hOEuL
yBgIRqFDcW5LGBDY5gjBdmNiIFuyoKkhE+Y16doC8ktAIU9VS7QVsi3tPQDomYeb
CWhR+Eg2VO9tQCOCXA==
=mShb
-----END PGP PUBLIC KEY BLOCK-----
.Ed
.
.Sh SEE ALSO
.Bl -bullet
.It
.Lk https://causal.agency "site that made me love manuals"
.It
.Lk https://stp.nakidai.ru stp
.It
.Lk https://latexds.nakidai.ru latexds
.It
.Lk https://nakidai.ru/cstyle.html cstyle(7)
.It
.Lk https://pwn3t.ru "cool domain"
.El
