.Dd August 24, 2024
.Dt NAKIDAI.RU 7
.Os Nakidai
.
.Sh NAME
.Nm nakidai
.Nd C & Python developer
.
.Sh SYNOPSIS
.Nm mail
.Mt plaza521@inbox.ru
.
.Sh DESCRIPTION
I'm coder from Russia.
I used to like playing games,
but now I'm tired of it a little I think.
.
.Pp
I'm writing my projects mostly in Python,
but sometime on dark nights
I want to relax and write something in C.
Usually,
after several hours since I started coding,
I will go cry because of my stupidness
and then close to morning I will go sleep.
.
.Pp
This is links to places
where you can find me:
.Bl -bullet
.It
.Lk https://discord.com/users/596659213124763649 discord
.It
.Lk https://git.nakidai.ru/nakidai gitea
.It
.Lk https://github.com/nakidai github
.El
.
.Pp
Also since I'm coder,
I write some projects.
There you can find some:
.Bl -tag -width Ds
.It Lk https://github.com/latexds LaTeXDS
LaTeX renderer in Discord
.It Lk https://github.com/nakidai/stp stp
SVG renderer in web
.It Lk https://github.com/nakidai/NotABot NotABot
QoL bot for Vectozavr's Discord server
.It Lk https://github.com/nakidai/MQEC MQEC
.Lk https://github.com/UltraQbik/SMC-MQ-CPU MQ
emulator
.It Lk https://git.nakidai.ru/nakidai/mycfetch mycfetch
Simple system fetch tool
.El
.
.Pp
Also there
you can see my key
which I use
for signing commits:
.Bl -bullet
.It
.Lk https://nakidai.ru/pubkey.asc link
.El
.Bd -literal
-----BEGIN PGP PUBLIC KEY BLOCK-----
Comment: Nakidai <plaza521@inbox.ru>
Comment:   C & Python developer
Comment: Fingerprint:   A0294D0C6040EFAA74F538C718AD605FDA13FE5A


mDMEZeYYIhYJKwYBBAHaRw8BAQdAW2JvE2Q+Bv2vJ3r9ZXqeFXS4HllW6A79G6Wr
ay3Gr260Mk5ha2lkYWkgKEMgJiBQeXRob24gZGV2ZWxvcGVyKSA8cGxhemE1MjFA
aW5ib3gucnU+iJMEExYKADsWIQSgKU0MYEDvqnT1OMcYrWBf2hP+WgUCZeYYIgIb
AwULCQgHAgIiAgYVCgkICwIEFgIDAQIeBwIXgAAKCRAYrWBf2hP+WgctAP9U/M/S
3F4Cls4CQgmsErAYmfRQ2UKYC1fQVeg16yZT/AEAjZRoAFnf3J/fb7rByPsW454v
hVmB+tNyVDeqqQ0xage4OARl5hgiEgorBgEEAZdVAQUBAQdATk8I26tjHH2+PtpA
kG/I+GmxWJqqjWcsm0WL68MJa3cDAQgHiHgEGBYKACAWIQSgKU0MYEDvqnT1OMcY
rWBf2hP+WgUCZeYYIgIbDAAKCRAYrWBf2hP+WqZWAP46h/hgCJZF+XKs8/djVs7b
RrWbuSGUxxPc7SVzL+yrEAD8C1SSfs+uWTgUTEIeIZ/QHtkUTEH8wcgmfHIGRUYE
SwA=
=Limc
-----END PGP PUBLIC KEY BLOCK-----
.Ed
.
.Sh SEE ALSO
.Bl -bullet
.It
.Lk https://causal.agency "Site that made me love manuals"
.It
.Lk https://stp.nakidai.ru stp
.It
.Lk https://latexds.nakidai.ru latexds
.It
.Lk https://nakidai.ru/cstyle.html cstyle(1)
.El
