.Dd May 10, 2025
.Dt ABOUT 7
.Os thoughts
.
.Sh NAME
.Nm about
.Nd my first article here ever
.
.Sh DESCRIPTION
So,
now there's a place
where I can post my articles.
Some people tell me
they wouldn't mind reading my articles
plus I would like to write them
even if for myself.
So
though I don't know
.Pq yet
what to write about
and my writing skills are not good at all,
having a determined place for public thoughts
sounds like a good idea as for me.
.
.Pp
Also
it's interesting for me to see
how obsessed I am with
.Lk https://causal.agency .
I like June's stuff so much,
I see her as an example for myself.
I wouldn't be there without her \(em
my thoughts
are one way or another based on what June writes,
I use many tools
she uses too
etc.
Honestly,
I think I steal from her too much.
If you'll ever find me and read this text
I hope you don't mind :3
.
.Pp
All the code of this website including articles
is open and is available in
my repo on github.
Actually, I like open source very much.
Isn't that nice
when your code can be viewed by anyone
and they can modify it for their needs?
I like suckless' projects from this POV,
their software can be examined and patched
without too much effort
and be useful in the end.
.
.Pp
Anyway,
I hope this article is not the last one here.
.
.Sh SEE ALSO
.Lk https://github.com/nakidai/nakidai.ru "site sources"
.
.Sh AUTHORS
.An Nakidai Perumenei Aq Mt nakidai@disroot.org
